# pipeline to create a resource group and deploy the key vault template

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'atest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Create a resource group.
        az group create --name keyVaultRG --location westeurope

        # deploy key vault template
        az deployment group create --resource-group keyVaultRG --template-file keyvault.bicep --parameters keyvault1.bicepparam
